Vagrant.configure("2") do |config|

    config.vm.box = "codecool/ubuntu-18.04-base"
    config.vm.provider "virtualbox"
    config.vm.provision :shell, path: "provision.sh"
    config.vm.synced_folder "..", "/home/vagrant/synced/"
end