version: '3.3'

services:
  web1:
    build: ..
    environment:
      - DEMO_NAME=Web1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://3.74.231.211:11201/chinook
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    restart: always
    ports:
      - "8081:8080"
