version: '3'
services:
  db:
    image: postgres:11
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./chinook_data.sql:/docker-entrypoint-initdb.d/chinook_data.sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chinook
    ports:
      - "5432:5432"
            
volumes:
  db_data: 
  